//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF0493_e3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public string isbn { get; set; }
        public string titulo { get; set; }
        public System.DateTime fcompra { get; set; }
        public bool baja { get; set; }
        public string sinopsis { get; set; }
    }
}
